"""Initial Database

Revision ID: 292cba21c6ea
Revises: 
Create Date: 2026-04-20 14:45:38.588771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292cba21c6ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accidents',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.Time(), nullable=False),
    sa.Column('road_type', sa.String(length=50), nullable=False),
    sa.Column('location_zone', sa.String(length=50), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('road_condition', sa.String(length=50), nullable=False),
    sa.Column('stray_animals', sa.Boolean(), nullable=True),
    sa.Column('wrong_way', sa.Boolean(), nullable=True),
    sa.Column('overloaded', sa.Boolean(), nullable=True),
    sa.Column('dui_alcohol', sa.Boolean(), nullable=True),
    sa.Column('helmet_seatbelt', sa.Boolean(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('driver_age', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('ambulance_eta', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accidents')
    # ### end Alembic commands ###
